### ISSUE TITLE
Індивідуальне завдання №2 з математичної статистики

### ISSUE THREAD

**Issue by MSH63ack** [MaxPayne5100/IT-technology#10]
@MaxPayne5100 Привіт) Які у тебе закони розподілу для критерію Пірсона?

**Comment by MaxPayne5100** [comment]
Привіт. Мені випало працювати з рівномірним законом розподілу та законом Пуассона.

**Comment by MSH63ack** [comment]
О, я якраз не знаю, як правильно робити частину завдання із розподілом Пуассона, оскільки мені теж випало з ним працювати. Ти можеш мені надіслати конспект або посилання на ресурс із поясненням?

**Comment by MaxPayne5100** [comment]
@MSH63ack  Привіт. Мені випало працювати з рівномірним законом розподілу та законом Пуассона.

**Comment by MSH63ack** [comment]
@MSH63ack О, я якраз не знаю, як правильно робити частину завдання із розподілом Пуассона, оскільки мені теж випало з ним працювати. Ти можеш мені надіслати конспект або посилання на ресурс із поясненням?

**Comment by MSH63ack** [comment]
@MaxPayne5100 О, я якраз не знаю, як правильно робити частину завдання із розподілом Пуассона, оскільки мені теж випало з ним працювати. Ти можеш мені надіслати конспект або посилання на ресурс із поясненням?

**Comment by MaxPayne5100** [comment]
@MSH63ack  Я брав інформацію з цього ресурсу: http://yukhym.com/uk/zakoni-rozpodilu/zakon-rozpodilu-puassona-zadachi.html
Дуже хороший сайт, особливо мені подобається наявність практичних завдань.

**Comment by MSH63ack** [comment]
@MaxPayne5100 Дуже дякую за інформацію!!!
