### ISSUE TITLE
Підготовка робочого столу

### ISSUE THREAD

**Issue by MSH63ack** [MaxPayne5100/IT-technology#11]
Необхідно виділити місце на робочому столі і прибрати зайві речі.

**Comment by MSH63ack** [comment]
@MaxPayne5100 Потрібно узгодити **розміри ноутбука** та **додаткових предметів**, щоб визначити чи буде достатньо місця на робочому столі.

**Comment by MaxPayne5100** [comment]
@MSH63ack Найбільш популярні є ноутбуки з діагоналлю екрана 15 дюймів. Особисто в мене є такий ноутбук і в нього розмір 360.7х243.6х15.9 мм, такі розміри є цілком прийнятні навіть якщо робоче місце є доволі обмежене.

**Comment by MSH63ack** [comment]
@MaxPayne5100 , дякую за пораду, отже, найбільш оптимальний розмір робочого місця - 1м.
Зайві речі вже прибрано.
Підготовка пройшла вдало.
