### ISSUE TITLE
Процесор

### ISSUE THREAD

**Issue by MaxPayne5100** [MaxPayne5100/IT-technology#14]
Процесор - основний компонент комп'ютера, призначений для керування всіма його пристроями, тому важливо зробити правильний вибір. На ринку процесорів для ноутбуків фігурують дві компанії Intel та AMD. Процесори Intel є популярніші та користувачі відзначають, що ці процесори менш схильні до нагрівання.

**Comment by MaxPayne5100** [comment]
Також найкраще брати нові процесори, особливо з техпроцесом - 14 нм.

**Comment by MaxPayne5100** [comment]
@MSH63ack , як гадаєш це хороший варіант [Intel Core i5-6500 (BX80662I56500)](https://github.com/MaxPayne5100/IT-technology/pull/23) ? Є ще якісь пропозиції ?

**Comment by MSH63ack** [comment]
@MaxPayne5100 , думаю, твій варіант хороший, але можна ще розглянути такий:
[Intel Core i7-8700 3.2GHz/8GT/s/12MB (BX80684I78700) s1151 BOX](https://github.com/MaxPayne5100/IT-technology/blob/master/processor_2)

**Comment by MaxPayne5100** [comment]
@MSH63ack , твій варіант хоча і дорожчий, але без сумніву кращий, тому давай візьмемо цей процесор.
