### ISSUE TITLE
Дисплей

### ISSUE THREAD

**Issue by MaxPayne5100** [MaxPayne5100/IT-technology#15]
Загалом TN+Film та IPS - найпопулярніші матриці для ноутбука. Я пропоную IPS, бо хоча це і дорожчий варіант, але тут ми отримуємо найкращу передачу кольорів.

**Comment by MaxPayne5100** [comment]
Також важливим елементом є розширення екрану, де лідером виступають ноутбуки з Full HD екраном.

**Comment by MSH63ack** [comment]
Оберемо Full HD екран на 15 дюймів. Так буде найкраще 😄
