### ISSUE TITLE
Відеокарта

### ISSUE THREAD

**Issue by MaxPayne5100** [MaxPayne5100/IT-technology#16]
По стандарту в ноутбуках в процесор вшита відеокарта, яку називають інтегрована, але для складних візуальних ефектів користувачі купують ноутбуки ще й з дискретною відеокартою, але це звісно виходить дорожче і до того ж для навчання інтегрованої графіки вистачатиме на роки.

**Comment by MaxPayne5100** [comment]
@MSH63ack  А от для роботи у сфері програмування інтегрованої графіки вистачатиме, якщо брати відрізок в 5 років?

**Comment by MSH63ack** [comment]
@MaxPayne5100 Це залежить від того, наскільки потужна інтегровна графіка, а також від галузі програмування, але загалом її вистачатиме для більшості категорій програмістів.

**Comment by MSH63ack** [comment]
#20 - доволі непоганий варіант) Є якісь ще пропозиції, @MaxPayne5100 ?

**Comment by MaxPayne5100** [comment]
[я тут](https://github.com/MaxPayne5100/IT-technology/pull/21)

**Comment by MSH63ack** [comment]
@MaxPayne5100 , як тобі відеокарта [Inno3D nVidia GeForce GTX 1080 Ti iChill HerculeZ X2 11GB GDDR5X 352bit (N108T-1SDN-Q6MN)](https://github.com/MaxPayne5100/IT-technology/pull/20) ?
Є ще якісь пропозиції?

**Comment by MaxPayne5100** [comment]
@MSH63ack , хороший варіант, але є дешевші, наприклад, [Palit nVidia GeForce GTX 1050 Ti StormX 4GB GDDR5 128bit](https://github.com/MaxPayne5100/IT-technology/pull/21).

**Comment by MSH63ack** [comment]
@MaxPayne5100 , погоджуюсь, це й справді кращий варіант. Отже, беремо цю відеокарту)
