### ISSUE TITLE
Спосіб купівлі

### ISSUE THREAD

**Issue by MSH63ack** [MaxPayne5100/IT-technology#17]
Існує **два** основні **способи купівлі**: через _інтернет-магазин_ та _локально_.
Кожен з них має свої переваги та недоліки. Серед основних _переваг_ інтернет-покупок: зручність, можливість доставки, можливість поверхневої оцінки всіх наявних на складі товарів.
_Переваги_ локальних покупок: більша впевненість у виборі та більші гарантії якості товару, повернення товару у випадку його несправності.

**Comment by MSH63ack** [comment]
Для здійснення покупки через інтернет або локально пропоную магазин [Brain](https://brain.com.ua/ukr/#)

**Comment by MSH63ack** [comment]
@MaxPayne5100 Які твої пропозиції щодо способу та місця покупки?

**Comment by MaxPayne5100** [comment]
@MSH63ack  Я гадаю, що купівля через інтернет-магазин буде найкращим вибором, перш за все через зручність, а саме можливість покупки у будь-якому місці світу.
