### ISSUE TITLE
Пам'ять

### ISSUE THREAD

**Issue by MaxPayne5100** [MaxPayne5100/IT-technology#18]
Оскільки ми шукаємо наш ноутбук для навчання та роботи, то потрібно подбати про сховище для зберігання важливих даних. Звісно чим більше сховище, тим краще. Важливо також вибрати накопичувач: SSD або HDD. Я рекомендую SSD при більших запасах коштів, оскільки він суттєве швидший від HDD, а також енергоспоживання твердотільних накопичувачів значно нижче , ніж у жорстких дисків.

**Comment by MaxPayne5100** [comment]
За посиланням нижче показано переваги та недоліки обидвох накопичувачів
https://lenovo.ua/blog/hdd-chi-ssd-dlya-noutbuka-u-chomu-vidminnosti-ce-spravdi-potribno-znati-shob-kupiti-noutbuk

**Comment by MaxPayne5100** [comment]
@MSH63ack Як гадаєш чи справді варто витратити більше грошей на SSD чи взагалі найкраще брати ноутбуки з наявним і SSD, і HDD ?

**Comment by MSH63ack** [comment]
@MaxPayne5100 Я вважаю, що найкраще обирати ноутбук із вбудованим HDD та SSD, оскільки HDD кращий для зберігання даних, а SSD — для роботи.
