### ISSUE TITLE
Місце купівлі

### ISSUE THREAD

**Issue by MSH63ack** [MaxPayne5100/IT-technology#19]
@MaxPayne5100 Потрібно визначити місце купівлі ноутбука. Для покупки через інтернет або локально пропоную магазин [Brain](https://brain.com.ua/ukr/#). Наскільки мені відомо, там не надто високі ціни та доволі хороший сервіс. Можливо, є якісь інші пропозиції?

**Comment by MaxPayne5100** [comment]
@MSH63ack Власне я багато замовляв в інтернет-магазині [Розетка](https://rozetka.com.ua/ua/). Там доволі низькі ціни, зручний сайт та широкий вибір товарів.

**Comment by MSH63ack** [comment]
@MaxPayne5100 , отже, судячи з вибраного магазину, ми одразу вибрали і спосіб купівлі #17 
Переглянути можна [тут](https://github.com/MaxPayne5100/IT-technology/blob/master/place_and_method) !
